site_name: Ciberseguridad

site_url: https://erickmarquez7.github.io

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.expand # despliega las subecciones
    - navigation.tabs #las secciones aparecen en la parte superior
    - navigation.sections #agrupa
    - navigation.top #boton de volver arriba 
    - search.highlight #resalta al buscar
    - toc.integrate #slidebar
    - content.tabs.link  #sincroniza tabs

markdown_extensions: 
  - admonition #las adevertencias verde, amarillo, rojo
  - pymdownx.details #colapsar
  - pymdownx.highlight #mejora color
  - pymdownx.superfences #para bloques de codigo
  - pymdownx.inlinehilite #codigo inline
  - pymdownx.tabbed #tablas
  

nav:
  - Home: index.md

  - Reportes & write-ups:
    - Hack The Box:
      - Plantilla: ryw/htb/ejemplo.md

    - Try Hack Me:
      - Net Sec: ryw/thm/netsec.md
      - TakeOver: ryw/thm/takeover.md
      - Agent T: prueba/prueba.md

  - Notas & Cheatsheets: 
    - My personal Road Map: notasych/myrmap.md
    - Reconocimiento: notasych/recon.md

  - Rabbit Holes:
    - Curiosidades: ruta/a/seguir/ejemplo.md
